version: 2
updates:
  # Maintain dependencies for npm in the frontend directory
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # Maintain dependencies for npm in the frontend-darknights directory
  - package-ecosystem: "npm"
    directory: "/frontend-darknights"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # Maintain dependencies for npm in the functions directory
  - package-ecosystem: "npm"
    directory: "/functions"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # Maintain github actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
