const fs = require('fs');
const path = require('path');

const dictionaries = {
  'pt': {
    'city.hello': 'Olá',
    'city.super_admin': 'Painel Mestre',
    'city.admin': 'Admin',
    'city.logout': 'Sair',
    'city.near_you': 'Perto de você',
    'city.approx_location': 'Localização aproximada',
    'city.where_going': 'Onde você vai?',
    'city.choose_spot': 'Escolha o seu lugar',
    'city.my_wallet': 'Minha Carteira',
    'city.tickets_passes': 'Ingressos e passes',
    'city.chats': 'Chats',
    'city.pending_messages': 'Mensagens pendentes',
    'city.visits': 'Visitas',
    'city.who_saw_you': 'Quem viu você',
    'city.install_app': 'Instalar App',
    'city.take_home': 'Leve Blow Nights na sua tela inicial',
    'city.vip_account': 'Sua Conta VIP',
    'city.go_premium': 'Seja Premium',
    'city.enjoy_advantages': 'Aproveite todas as vantagens',
    'city.see_plans': 'Ver planos e benefícios',
    'city.see_more': 'Ver mais',
    'city.vip_active_features': 'Recursos VIP Ativos',
    'city.incognito_mode': 'Modo Incógnito',
    'city.navigate_hidden': 'Navegue sem deixar rastro',
    'city.daily_boost': 'Boost Diário',
    'city.more_visibility': 'Mais visibilidade no mapa',
    'city.used': 'Usado',
    'city.activate_boost': 'Ativar Boost'
  },
  'ca': {
    'city.hello': 'Hola',
    'city.super_admin': 'Panell Mestre',
    'city.admin': 'Admin',
    'city.logout': 'Sortir',
    'city.near_you': 'A prop teu',
    'city.approx_location': 'Ubicació aproximada',
    'city.where_going': 'On surts?',
    'city.choose_spot': 'Tria el teu lloc',
    'city.my_wallet': 'La meva Cartera',
    'city.tickets_passes': 'Entrades i passis',
    'city.chats': 'Xats',
    'city.pending_messages': 'Missatges pendents',
    'city.visits': 'Visites',
    'city.who_saw_you': 'Qui t\'ha vist',
    'city.install_app': 'Instal·lar App',
    'city.take_home': 'Porta Blow Nights a la teva pantalla d\'inici',
    'city.vip_account': 'El teu Compte VIP',
    'city.go_premium': 'Fes-te Premium',
    'city.enjoy_advantages': 'Gaudeix de tots els avantatges',
    'city.see_plans': 'Veure plans i beneficis',
    'city.see_more': 'Veure més',
    'city.vip_active_features': 'Funcions VIP Actives',
    'city.incognito_mode': 'Mode Incògnit',
    'city.navigate_hidden': 'Navega sense deixar rastre',
    'city.daily_boost': 'Boost Diari',
    'city.more_visibility': 'Més visibilitat al mapa',
    'city.used': 'Usat',
    'city.activate_boost': 'Activar Boost'
  },
  'fr': {
    'city.hello': 'Bonjour',
    'city.super_admin': 'Panneau Principal',
    'city.admin': 'Admin',
    'city.logout': 'Se déconnecter',
    'city.near_you': 'Près de vous',
    'city.approx_location': 'Emplacement approximatif',
    'city.where_going': 'Où allez-vous?',
    'city.choose_spot': 'Choisissez votre endroit',
    'city.my_wallet': 'Mon Portefeuille',
    'city.tickets_passes': 'Billets et pass',
    'city.chats': 'Discussions',
    'city.pending_messages': 'Messages en attente',
    'city.visits': 'Visites',
    'city.who_saw_you': 'Qui vous a vu',
    'city.install_app': 'Installer l\'App',
    'city.take_home': 'Ajoutez Blow Nights à votre écran d\'accueil',
    'city.vip_account': 'Votre Compte VIP',
    'city.go_premium': 'Devenir Premium',
    'city.enjoy_advantages': 'Profitez de tous les avantages',
    'city.see_plans': 'Voir les plans et avantages',
    'city.see_more': 'Voir plus',
    'city.vip_active_features': 'Fonctionnalités VIP Actives',
    'city.incognito_mode': 'Mode Incognito',
    'city.navigate_hidden': 'Naviguez sans laisser de trace',
    'city.daily_boost': 'Boost Quotidien',
    'city.more_visibility': 'Plus de visibilité sur la carte',
    'city.used': 'Utilisé',
    'city.activate_boost': 'Activer le Boost'
  },
  'it': {
    'city.hello': 'Ciao',
    'city.super_admin': 'Pannello Principale',
    'city.admin': 'Admin',
    'city.logout': 'Esci',
    'city.near_you': 'Vicino a te',
    'city.approx_location': 'Posizione approssimativa',
    'city.where_going': 'Dove vai?',
    'city.choose_spot': 'Scegli il tuo locale',
    'city.my_wallet': 'Il Mio Portafoglio',
    'city.tickets_passes': 'Biglietti e pass',
    'city.chats': 'Chat',
    'city.pending_messages': 'Messaggi in sospeso',
    'city.visits': 'Visite',
    'city.who_saw_you': 'Chi ti ha visto',
    'city.install_app': 'Installa App',
    'city.take_home': 'Porta Blow Nights nella tua schermata home',
    'city.vip_account': 'Il Tuo Account VIP',
    'city.go_premium': 'Diventa Premium',
    'city.enjoy_advantages': 'Goditi tutti i vantaggi',
    'city.see_plans': 'Vedi piani e vantaggi',
    'city.see_more': 'Vedi altro',
    'city.vip_active_features': 'Funzioni VIP Attive',
    'city.incognito_mode': 'Modalità Incognito',
    'city.navigate_hidden': 'Naviga senza lasciare tracce',
    'city.daily_boost': 'Boost Giornaliero',
    'city.more_visibility': 'Maggiore visibilità sulla mappa',
    'city.used': 'Usato',
    'city.activate_boost': 'Attiva Boost'
  },
  'el': {
    'city.hello': 'Γεια σου',
    'city.super_admin': 'Κύριος Πίνακας',
    'city.admin': 'Διαχειριστής',
    'city.logout': 'Αποσύνδεση',
    'city.near_you': 'Κοντά σου',
    'city.approx_location': 'Κατά προσέγγιση τοποθεσία',
    'city.where_going': 'Πού πηγαίνεις;',
    'city.choose_spot': 'Επίλεξε το μέρος σου',
    'city.my_wallet': 'Το Πορτοφόλι Μου',
    'city.tickets_passes': 'Εισιτήρια και πάσα',
    'city.chats': 'Συνομιλίες',
    'city.pending_messages': 'Εκκρεμή μηνύματα',
    'city.visits': 'Επισκέψεις',
    'city.who_saw_you': 'Ποιος σε είδε',
    'city.install_app': 'Εγκατάσταση App',
    'city.take_home': 'Πρόσθεσε το Blow Nights στην αρχική οθόνη',
    'city.vip_account': 'Ο VIP Λογαριασμός σου',
    'city.go_premium': 'Γίνε Premium',
    'city.enjoy_advantages': 'Απόλαυσε όλα τα πλεονεκτήματα',
    'city.see_plans': 'Δες προγράμματα και προνόμια',
    'city.see_more': 'Δες περισσότερα',
    'city.vip_active_features': 'Ενεργές Λειτουργίες VIP',
    'city.incognito_mode': 'Ανώνυμη Περιήγηση',
    'city.navigate_hidden': 'Περιηγήσου χωρίς ίχνη',
    'city.daily_boost': 'Ημερήσιο Boost',
    'city.more_visibility': 'Περισσότερη ορατότητα στον χάρτη',
    'city.used': 'Χρησιμοποιήθηκε',
    'city.activate_boost': 'Ενεργοποίηση Boost'
  },
  'ru': {
    'city.hello': 'Привет',
    'city.super_admin': 'Главная панель',
    'city.admin': 'Админ',
    'city.logout': 'Выйти',
    'city.near_you': 'Рядом с вами',
    'city.approx_location': 'Примерное местоположение',
    'city.where_going': 'Куда ты идешь?',
    'city.choose_spot': 'Выбери свое место',
    'city.my_wallet': 'Мой кошелек',
    'city.tickets_passes': 'Билеты и пропуска',
    'city.chats': 'Чаты',
    'city.pending_messages': 'Ожидающие сообщения',
    'city.visits': 'Визиты',
    'city.who_saw_you': 'Кто вас видел',
    'city.install_app': 'Установить приложение',
    'city.take_home': 'Добавьте Blow Nights на главный экран',
    'city.vip_account': 'Ваш VIP-аккаунт',
    'city.go_premium': 'Стать Premium',
    'city.enjoy_advantages': 'Наслаждайтесь всеми преимуществами',
    'city.see_plans': 'Посмотреть планы и бонусы',
    'city.see_more': 'Узнать больше',
    'city.vip_active_features': 'Активные VIP-функции',
    'city.incognito_mode': 'Режим инкогнито',
    'city.navigate_hidden': 'Просматривайте без следов',
    'city.daily_boost': 'Ежедневный Boost',
    'city.more_visibility': 'Больше видимости на карте',
    'city.used': 'Использовано',
    'city.activate_boost': 'Активировать Boost'
  },
  'ar': {
    'city.hello': 'مرحباً',
    'city.super_admin': 'اللوحة الرئيسية',
    'city.admin': 'مسؤول',
    'city.logout': 'تسجيل خروج',
    'city.near_you': 'بالقرب منك',
    'city.approx_location': 'الموقع التقريبي',
    'city.where_going': 'إلى أين تذهب؟',
    'city.choose_spot': 'اختر مكانك',
    'city.my_wallet': 'محفظتي',
    'city.tickets_passes': 'تذاكر وتصاريح',
    'city.chats': 'محادثات',
    'city.pending_messages': 'رسائل قيد الانتظار',
    'city.visits': 'الزيارات',
    'city.who_saw_you': 'من شاهدك',
    'city.install_app': 'تثبيت التطبيق',
    'city.take_home': 'أضف Blow Nights إلى شاشتك الرئيسية',
    'city.vip_account': 'حساب الـ VIP الخاص بك',
    'city.go_premium': 'احصل على Premium',
    'city.enjoy_advantages': 'استمتع بجميع المزايا',
    'city.see_plans': 'عرض الخطط والمزايا',
    'city.see_more': 'رؤية المزيد',
    'city.vip_active_features': 'ميزات VIP النشطة',
    'city.incognito_mode': 'وضع التخفي',
    'city.navigate_hidden': 'تصفح بدون ترك أثر',
    'city.daily_boost': 'التعزيز اليومي',
    'city.more_visibility': 'مزيد من الظهور على الخريطة',
    'city.used': 'مستخدم',
    'city.activate_boost': 'تفعيل التعزيز'
  }
};

for (const [lang, translations] of Object.entries(dictionaries)) {
  const filePath = path.join(__dirname, 'src/i18n/locales', `${lang}.json`);
  if (fs.existsSync(filePath)) {
    const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
    const newData = { ...data, ...translations };
    fs.writeFileSync(filePath, JSON.stringify(newData, null, 2));
  }
}
